AllCops:
  Exclude:
    - vendor/**

AlignParameters:
  Enabled: true
Encoding:
  Enabled: false
HashSyntax:
  Enabled: true
LineLength:
  Enabled: false
MethodLength:
  Max: 30

SingleSpaceBeforeFirstArg:
  Enabled: false
CommentIndentation:
  Enabled: false
